[package]
name = "udp-over-tcp"
version = "0.1.0"
authors = ["Alex Williams <mkb2191@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
